"""removed unique attributes

Revision ID: 76c3fd7a5953
Revises: 97e8e71e73f7
Create Date: 2020-04-30 22:21:54.688196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c3fd7a5953'
down_revision = '97e8e71e73f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phonenumber', table_name='user')
    op.create_index(op.f('ix_user_phonenumber'), 'user', ['phonenumber'], unique=False)
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_index(op.f('ix_user_phonenumber'), table_name='user')
    op.create_index('ix_user_phonenumber', 'user', ['phonenumber'], unique=1)
    # ### end Alembic commands ###
