"""added address

Revision ID: 97e8e71e73f7
Revises: ad56d2ab7c2d
Create Date: 2020-04-30 22:14:45.210506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e8e71e73f7'
down_revision = 'ad56d2ab7c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('propertyaddress', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_user_propertyaddress'), 'user', ['propertyaddress'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_propertyaddress'), table_name='user')
    op.drop_column('user', 'propertyaddress')
    # ### end Alembic commands ###
